### PR TITLE
Makes Project GPLv3 Compatable

### LINKED ISSUE #7: License for project
I need to decide on this

### PR DESCRIPTION
**Pull request by Krutonium**
Fixes #7 ;)

### CODE REVIEW

**Comment by emmatyping** [comment]
Did you try running this? iirc, I made a custom style that is needed by the app

**Comment by Krutonium** [comment]
Worked fine.

**Comment by Krutonium** [comment]
pic

**Comment by Krutonium** [comment]
It should be noted this also reduces compile time and makes source download quicker.

**Comment by emmatyping** [comment]
Can you add a license file and a note about license in the readme please? Looks good

**Comment by Krutonium** [comment]
Sure, 20 sec.

**Comment by Krutonium** [comment]
Done

**Comment by emmatyping** [comment]
The problem is that there are 2 close buttons in the image you posted.

**Pull request merged**
